title: Julia M. Smith
description: Experimental social psychologist studying morality and the self concept.
show_downloads: true
google_analytics:
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
logo_url: 
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://julia-m-smith.github.io/Smith_CV2025.pdf
  zip_title: View my CV
  tar_url: https://julia-m-smith.github.io/teaching.html
  tar_title: Teaching
  res_url: https://julia-m-smith.github.io/research.html
  res_title: Research
  zip_hide: false
  tar_hide: false
  res_hide: false


