title: Julia M. Smith
description: Experimental social psychologist studying morality and the self concept.
show_downloads: true
google_analytics:
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
logo_url: 
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css


